---
title: Proyecto AED
author:
  - name: Inés Esteve Mompó
  - name: Azael
  - name: Manuel
journal: notspecified
type: article
simplesummary: En este proyecto, vamos a analizar el número de préstamos y devoluciones de las bicicletas de 'ValenBisi' durante el año 2022 en cada una de sus estaciones ubicadas por toda la ciudad de Valencia. También compararemos, entre otras cosas, la posible influencia que puede tener, sobre el alquiler de estas bicicletas, estar cerca de otros medios de transporte público de la ciudad como podría ser el ejemplo de 'MetroValencia'.
endnotes: false
output: 
  rticles::mdpi_article:
    extra_dependencies: longtable
---


# Introducción. Descripción del proyecto

Vamos a analizar el número de préstamos y devoluciones de las bicicletas de 'ValenBisi' durante el año 2022 en cada una de sus estaciones ubicadas por toda la ciudad de Valencia. También compararemos, entre otras cosas, la posible influencia que puede tener, sobre el alquiler de estas bicicletas, estar cerca de otros medios de transporte público de la ciudad como podría ser el ejemplo de 'MetroValencia'.

El trabajo partirá a través de 2 conjuntos de datos, más tarde se podrán incluir otros para hacer futuras comparaciones de nuestros datos. El dataset principal sobre el que trabajaremos, llamado 'ValenBisi_2022.csv' que podemos encontrar en https://datos.gob.es/es/catalogo/l01462508-valenbisi-2022-alquileres-y-devoluciones, muestra los datos del problema que anteriormente hemos detallado, el número de préstamos y devoluciones de las bicicletas de 'ValenBisi' durante el año 2022. En cambio, el otro dataset que vamos a hacer servir, 'ValenBisi_disponibilidad.csv', que podemos encontrar en https://datos.gob.es/es/catalogo/l01462508-valenbisi-disponibilidad y que se actualiza cada 10 minutos, será usado únicamente con la finalidad de recoger la información de dos de sus filas, concretamente aquellas que muestran las coordenadas geográficas de cada una de las estaciones de bicicletas, para el posterior tratamiento de estas.
